version: '3.3'

services:
  spring-boot:
    image: "springio/inventory-management"
    ports:
      - "8080:8080"
    container_name: spring-boot
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    container_name: grafana
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    container_name: mongo
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
